### ISSUE TITLE
Attribute Error when integrating it on S3 and Lambda services. 

### ISSUE THREAD

**Issue by dhanjo** [abhinavbom/clara#5]
Hey,
I was doing some projects and I came across this open-source tool. When I  move forward to implement the code on lambda I am getting the following error:

`[ERROR] AttributeError: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/var/task/scan.py", line 68, in lambda_handler
    clamav_result = clamav.scan_file(file_path)
  File "/var/task/clamav.py", line 117, in scan_file
    detection = str1.group(4)`

I have no idea how can I solve this error. 
Thanks

**Comment by webbrain-one** [comment]
Hi! Thanks for reporting this issue. 👋

I've opened a pull request to fix this: https://github.com/abhinavbom/clara/pull/19

It looks like the regex match was returning `None` in your Lambda environment, which caused the `AttributeError` when trying to access the group. This PR adds a safety check to handle that case so the code doesn't crash.

Let me know if this resolves the error for you!
